select*from capstone.categories;
select*from capstone.brand;
select*from capstone.customers;
select*from capstone.order_items;
select*from capstone.orders_id;
select*from capstone.product;
select*from capstone.staff_id;
select*from capstone.stock;
select*from capstone.stores;

-- o Join orders, order_items, and products to display detailed line items. 

select o.order_id as order_id,o.customer_id as customer_id,o.order_status as order_status,p.product_id as product_id,p.category_id as category_id from capstone.orders_id as o
join capstone.order_items as oi
on o.order_id=oi.order_id
join capstone.product as p
on p.product_id=oi.product_id;

-- Total Sales by Store 
-- o Write a query to group sales (total_price) by each store_id. 

select sum(oi.total_price)as total_price,o.store_id as store_id from capstone.orders_id as o
join capstone.order_items as oi
on o.order_id=oi.order_id
group by store_id;

-- 5. Top 5 Selling Products 
-- o Use ORDER BY and LIMIT to get the top 5 most sold products by 
-- quantity.

select p.product_id as product_id, sum(oi.quantity) as total_quantity from capstone.order_items as oi
join capstone.product as p
on p.product_id=oi.product_id
group by product_id
order by total_quantity desc limit 5;

-- 6. Customer Purchase Summary 
-- o For each customer, return total orders placed, total items purchased, 
-- and total revenue.

select o.customer_id as customer_id,count(distinct(oi.order_id))as order_placed,sum(oi.quantity)as purchase,sum(oi.total_price)as total_revenue from capstone.order_items as oi
join capstone.orders_id as o
on o.order_id=oi.order_id
group by customer_id;

-- 7. Segment Customers by Total Spend 
-- o Write a query to classify customers into spending brackets (e.g., low, 
-- medium, high).

select customer_id,sum(oi.total_price) as total_spend,
case
when sum(oi.total_price)<=10000 then "low"
when sum(oi.total_price)<=35000 then "medium"
else"high"
end as customer_status from capstone.order_items as oi
join capstone.orders_id as o
on o.order_id=oi.order_id
group by customer_id;

-- 8. Staff Performance Analysis 
-- o Analyze total revenue generated by each staff member based on their 
-- handled orders.

select s.staff_id as staff_id,sum(oi.total_price) as total_revenue from capstone.orders_id as o
join capstone.order_items as oi
on o.order_id=oi.order_id
join capstone.staff_id as s
on o.staff_id=s.staff_id
group by staff_id;

-- 9. Stock Alert Query 
-- o Write a query to list products where stock quantity < 10 in any store.

select p.product_name as product_name, sum(sto.quantity) as stock_quantity,st.store_name as store_name from capstone.stock as sto
join capstone.product as p
on sto.product_id=p.product_id
join capstone.stores as st
on sto.store_id=st.stores_id
group by product_name,store_name
having sum (sto.quantity)<10;

-- to create final segementation table 
create table customer_segment(
customer_id int primary key,
recency int,
frequency int,
monetary double,
segment_label text);

select * from Capstone.customer_segment;

